export const movieMock = {
  adult: false,
  backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
  id: '566525',
  original_language: "en",
  original_title: "Shang-Chi and the Legend of the Ten Rings",
  overview: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
  popularity: 8300.401,
  poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
  release_date: "2021-09-01",
  title: "Shang-Chi and the Legend of the Ten Rings",
  video: false,
  vote_average: 7.9,
  vote_count: 3282,
}

export const moviesMock = [{
  adult: false,
  backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
  id: '566525',
  original_language: "en",
  original_title: "Shang-Chi and the Legend of the Ten Rings",
  overview: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
  popularity: 8300.401,
  poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
  release_date: "2021-09-01",
  title: "Shang-Chi and the Legend of the Ten Rings",
  video: false,
  vote_average: 7.9,
  vote_count: 3282,
}]